name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
      jobs:
        build_and_package:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                java-version: '19'
                distribution: 'temurin'
            - run: ls -la
            - name: Build with Maven
              run: mvn -B package --file pom.xml
